import { FORM_SERVICE_NAME } from 'src/utils/constants/enums';
import {
	basedOfPolesCard,
	basedOnBlueCard,
	basedOnBusinessFOP,
	basedOnBusinessTOV,
	basedOnFamily,
	basedOnHumanitarian,
	basedOnParents,
	basedOnStudy,
	basedOnWork,
	carRegistration,
	citizenshipGraduation,
	declarationOfIntentToWork,
	definitionOfCitizenship,
	euResidenceCard,
	familyMemberDataTemplate,
	gettingCertificationAndLicenses,
	insurance,
	licenceChange,
	noCriminalRecordCertificate,
	openingCompany,
	openingCompanyOwner,
	openingSoleProprietorship,
	pesel,
	polishCitizenMarriage,
	starostasInformation,
	tripsAbroadDataTemplate,
	virtualOfficeNo,
	virtualOfficeYes,
	workPermit,
} from 'src/utils/constants/formTemplatesData';

export const mainFormData: Record<string, string[] | []> = {
	// legalization of stay - legalization of work
	[FORM_SERVICE_NAME.WORK]: basedOnWork,
	[FORM_SERVICE_NAME.BLUE_CARD]: basedOnBlueCard,
	[FORM_SERVICE_NAME.LEARNING]: basedOnStudy,
	[FORM_SERVICE_NAME.BUSINESS_INDIVIDUAL]: basedOnBusinessFOP,
	[FORM_SERVICE_NAME.BUSINESS_LLC]: basedOnBusinessTOV,
	[FORM_SERVICE_NAME.LIVING_WITH_FAMILY]: basedOnFamily,
	[FORM_SERVICE_NAME.BELARUS_D21_VISA]: basedOnHumanitarian,
	[FORM_SERVICE_NAME.ABSOLVENTA]: citizenshipGraduation,
	[FORM_SERVICE_NAME.LIVING_WITH_BOYFRIEND]: basedOnParents,
	[FORM_SERVICE_NAME.RESIDENT_OF_EUROPEAN]: euResidenceCard,
	[FORM_SERVICE_NAME.POLAND_CARDS]: basedOfPolesCard,
	[FORM_SERVICE_NAME.ORIGIN_HISTORICAL_DOCUMENTS]: definitionOfCitizenship,
	[FORM_SERVICE_NAME.MARRIAGE_TO_POLISH_CITIZEN]: polishCitizenMarriage,
	[FORM_SERVICE_NAME.STATEMENT_OF_INTENT_WORK]: declarationOfIntentToWork,
	[FORM_SERVICE_NAME.INFORMATION_OF_STAROSTA]: starostasInformation,
	[FORM_SERVICE_NAME.WORK_PERMIT]: workPermit,
	// custom form in form template
	[FORM_SERVICE_NAME.FAMILY_MEMBER]: familyMemberDataTemplate,
	[FORM_SERVICE_NAME.TRIPS_ABROAD]: tripsAbroadDataTemplate,
	[FORM_SERVICE_NAME.OPENING_COMPANY_MEMBER]: openingCompanyOwner,
	// business consulting
	[FORM_SERVICE_NAME.OPENING_COMPANY]: openingCompany,
	[FORM_SERVICE_NAME.OPENING_SOLE_PROPRIETORSHIP]: openingSoleProprietorship,
	[FORM_SERVICE_NAME.VIRTUAL_OFFICE_YES]: virtualOfficeYes,
	[FORM_SERVICE_NAME.VIRTUAL_OFFICE_NO]: virtualOfficeNo,
	[FORM_SERVICE_NAME.GETTING_CERTIFICATION_AND_LICENSES]: gettingCertificationAndLicenses,
	// services for life
	[FORM_SERVICE_NAME.INSURANCE]: insurance,
	[FORM_SERVICE_NAME.CAR_REGISTRATION]: carRegistration,
	[FORM_SERVICE_NAME.PESEL]: pesel,
	[FORM_SERVICE_NAME.LICENCE_CHANGE]: licenceChange,
	[FORM_SERVICE_NAME.NO_CRIMINAL_RECORD_CERTIFICATE]: noCriminalRecordCertificate,
};
