import { FC, ReactNode } from 'react';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import { Footer } from 'src/components/Footer';
import { Header } from 'src/sections';
import styles from './index.module.scss';

interface Layout {
	children: ReactNode;
}

const inter = Inter({ subsets: ['latin'] });

const Layout: FC<Layout> = ({ children }): JSX.Element => {
	return (
		<div className={`${inter.className} ${styles.wrapper}`}>
			<Head>
				<title>Semeniaka Bot</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>

			<Header />
			<main className={styles.main}>{children}</main>
			<Footer />
		</div>
	);
};
export const withLayout = <T extends Record<string, unknown>>(Component: FC<T>) =>
	function withLayoutComponent(props: T): JSX.Element {
		return (
			<Layout>
				<Component {...props} />
			</Layout>
		);
	};
